# server.port=8181  :properties ???? ??


#yml ?? ??
server:
  port: 8181

logging:
  level:
    root: info    # ????? log ??? ??

    com:
      example:
        apibasic:
          req: info # ?? ???? log ??? ??

springdoc:
  swagger-ui:
    path: /myapi.html

#spring.data.source.url=xxx
#spring.data.source.username=xxx
#spring.data.source.password=xxx


#spirng:
#  datasource:
#    url: xxx
#    useranme: xxx
#    password: xxx

